### ISSUE TITLE
AOSmithAPIClient Raises RuntimeError: no running event loop

### ISSUE THREAD

**Issue by AlanLivingston** [bdr99/py-aosmith#5]
Running Python v3.13.0 64-bit version in a virtualenv created virtual environment.

I get the following error:

```
from py_aosmith import AOSmithAPIClient
from py_aosmith.models import OperationMode
client = AOSmithAPIClient("REDACTED@gmail.com", "REDACTED")
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    client = AOSmithAPIClient("REDACTED@gmail.com", "REDACTED")
  File "d:\water_heater_test\env\Lib\site-packages\py_aosmith\client.py", line 183, in __init__
    self.session = aiohttp.ClientSession()
  File "d:\water_heater_test\env\Lib\site-packages\aiohttp\client.py", line 310, in __init__
    loop = loop or asyncio.get_running_loop()
RuntimeError: no running event loop
```

**Comment by AlanLivingston** [comment]
Looks like a change to aiohttp.  See https://github.com/aio-libs/aiohttp/issues/8555

**Comment by AlanLivingston** [comment]
I think I was misunderstanding how to use the module.  I was able to get it running with some tweaks to the example:

```
async def test():
    async with aiohttp.ClientSession() as sess:
        client = AOSmithAPIClient('REDACTED@gmail.com', 'REDACTED', sess)
        
        info = await client.get_all_device_info()
        return info


if __name__ == "__main__":
    asyncio.run(test())
```
